
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import Slide from "@/Components/Slide";
import 'bootstrap/dist/css/bootstrap.css'
import Newarrival from "@/Components/Newarrival";
import Navbar2 from "@/Components/Navbar2";
import Test from "@/Components/Test";
import Navbar3 from "@/Components/Navbar3";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Utensils-store ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className={inter.className}>
     
        <Navbar2/>
   <Navbar3/>
   <Slide/>

    
        {children}</body>
    </html>
  );
}
